import { ServiceProvider, UserRole, Wilaya, PageView } from './types';

// Full list of 58 Wilayas
export const WILAYAS: Wilaya[] = [
  { id: 1, name: 'Adrar', latitude: 27.9748, longitude: -0.2031 },
  { id: 2, name: 'Chlef', latitude: 36.1652, longitude: 1.3345 },
  { id: 3, name: 'Laghouat', latitude: 33.8000, longitude: 2.8651 },
  { id: 4, name: 'Oum El Bouaghi', latitude: 35.8755, longitude: 7.1135 },
  { id: 5, name: 'Batna', latitude: 35.5559, longitude: 6.1741 },
  { id: 6, name: 'Béjaïa', latitude: 36.7509, longitude: 5.0556 },
  { id: 7, name: 'Biskra', latitude: 34.8600, longitude: 5.7272 },
  { id: 8, name: 'Béchar', latitude: 31.6181, longitude: -2.2142 },
  { id: 9, name: 'Blida', latitude: 36.4700, longitude: 2.8291 },
  { id: 10, name: 'Bouira', latitude: 36.3748, longitude: 3.9020 },
  { id: 11, name: 'Tamanrasset', latitude: 22.7862, longitude: 5.5228 },
  { id: 12, name: 'Tébessa', latitude: 35.4041, longitude: 8.1143 },
  { id: 13, name: 'Tlemcen', latitude: 34.8783, longitude: -1.3150 },
  { id: 14, name: 'Tiaret', latitude: 35.3710, longitude: 1.3169 },
  { id: 15, name: 'Tizi Ouzou', latitude: 36.7118, longitude: 4.0459 },
  { id: 16, name: 'Alger', latitude: 36.7528, longitude: 3.0420 },
  { id: 17, name: 'Djelfa', latitude: 34.6727, longitude: 3.2630 },
  { id: 18, name: 'Jijel', latitude: 36.8205, longitude: 5.7667 },
  { id: 19, name: 'Sétif', latitude: 36.1898, longitude: 5.4108 },
  { id: 20, name: 'Saïda', latitude: 34.8303, longitude: 0.1517 },
  { id: 21, name: 'Skikda', latitude: 36.8665, longitude: 6.9046 },
  { id: 22, name: 'Sidi Bel Abbès', latitude: 35.1899, longitude: -0.6308 },
  { id: 23, name: 'Annaba', latitude: 36.9009, longitude: 7.7669 },
  { id: 24, name: 'Guelma', latitude: 36.4621, longitude: 7.4260 },
  { id: 25, name: 'Constantine', latitude: 36.3650, longitude: 6.6147 },
  { id: 26, name: 'Médéa', latitude: 36.2641, longitude: 2.7539 },
  { id: 27, name: 'Mostaganem', latitude: 35.9397, longitude: 0.0897 },
  { id: 28, name: 'M\'Sila', latitude: 35.7050, longitude: 4.5423 },
  { id: 29, name: 'Mascara', latitude: 35.3966, longitude: 0.1402 },
  { id: 30, name: 'Ouargla', latitude: 31.9529, longitude: 5.3236 },
  { id: 31, name: 'Oran', latitude: 35.6971, longitude: -0.6308 },
  { id: 32, name: 'El Bayadh', latitude: 33.6831, longitude: 1.0192 },
  { id: 33, name: 'Illizi', latitude: 26.5058, longitude: 8.4815 },
  { id: 34, name: 'Bordj Bou Arréridj', latitude: 36.0707, longitude: 4.7597 },
  { id: 35, name: 'Boumerdès', latitude: 36.7598, longitude: 3.4721 },
  { id: 36, name: 'El Tarf', latitude: 36.7672, longitude: 8.3137 },
  { id: 37, name: 'Tindouf', latitude: 27.6711, longitude: -8.1474 },
  { id: 38, name: 'Tissemsilt', latitude: 35.6072, longitude: 1.8109 },
  { id: 39, name: 'El Oued', latitude: 33.3683, longitude: 6.8574 },
  { id: 40, name: 'Khenchela', latitude: 35.4358, longitude: 7.1433 },
  { id: 41, name: 'Souk Ahras', latitude: 36.2863, longitude: 7.9511 },
  { id: 42, name: 'Tipaza', latitude: 36.5897, longitude: 2.4475 },
  { id: 43, name: 'Mila', latitude: 36.4502, longitude: 6.2647 },
  { id: 44, name: 'Aïn Defla', latitude: 36.2588, longitude: 1.9673 },
  { id: 45, name: 'Naâma', latitude: 32.7557, longitude: -0.3036 },
  { id: 46, name: 'Aïn Témouchent', latitude: 35.2974, longitude: -1.1403 },
  { id: 47, name: 'Ghardaïa', latitude: 32.4909, longitude: 3.6734 },
  { id: 48, name: 'Relizane', latitude: 35.7402, longitude: 0.5525 },
  { id: 49, name: 'Timimoun', latitude: 29.2638, longitude: 0.2309 },
  { id: 50, name: 'Bordj Badji Mokhtar', latitude: 21.3277, longitude: 0.9537 },
  { id: 51, name: 'Ouled Djellal', latitude: 34.4280, longitude: 5.0673 },
  { id: 52, name: 'Béni Abbès', latitude: 30.1228, longitude: -2.1706 },
  { id: 53, name: 'In Salah', latitude: 27.1936, longitude: 2.4611 },
  { id: 54, name: 'In Guezzam', latitude: 19.5714, longitude: 5.7692 },
  { id: 55, name: 'Touggourt', latitude: 33.1062, longitude: 6.0658 },
  { id: 56, name: 'Djanet', latitude: 24.5551, longitude: 9.4831 },
  { id: 57, name: 'El M\'Ghair', latitude: 33.9535, longitude: 5.9221 },
  { id: 58, name: 'El Meniaa', latitude: 30.5858, longitude: 2.8756 },
];

export const COMMUNES: Record<number, string[]> = {
  1: ['Adrar', 'Tamest', 'Charouine', 'Reggane', 'Tsabit', 'Zaouiet Kounta', 'Aoulef', 'Timokten', 'Fenoughil'],
  2: ['Chlef', 'Ténès', 'El Karimia', 'Ouled Fares', 'Boukadir', 'Beni Rached', 'Chettia', 'Sidi Akkacha', 'Oued Fodda'],
  3: ['Laghouat', 'Ksar El Hirane', 'Bennasser Benchohra', 'Sidi Makhlouf', 'Hassi Delaa', 'Aflou', 'Ain Madhi'],
  4: ['Oum El Bouaghi', 'Ain Beida', 'Ain M\'lila', 'Ain Fakroun', 'Sigus', 'El Amiria', 'Meskiana', 'Dhala'],
  5: ['Batna', 'Barika', 'Merouana', 'Ain Touta', 'El Madher', 'Tazoult', 'N\'Gaous', 'Arris', 'Chemora'],
  6: ['Béjaïa', 'Amizour', 'Feraoun', 'Taourirt Ighil', 'Chellata', 'Tamokra', 'Akbou', 'Seddouk', 'Tichy', 'Aokas'],
  7: ['Biskra', 'Oumache', 'Branis', 'Chetma', 'Ouled Djellal', 'Tolga', 'Lioua', 'Sidi Okba', 'Zeribet El Oued'],
  8: ['Béchar', 'Kenadsa', 'Lahmar', 'Beni Ounif', 'Taghit', 'Abadla', 'Erg Ferradj', 'Ouled Khoudir'],
  9: ['Blida', 'Boufarik', 'Bougara', 'Bouinan', 'El Affroun', 'Larbaa', 'Meftah', 'Mouzaia', 'Oued El Alleug'],
  10: ['Bouira', 'Lakhdaria', 'Sour El Ghozlane', 'Ain Bessem', 'Kadiria', 'M\'Chedallah', 'Bechloul', 'El Hachimia'],
  11: ['Tamanrasset', 'Abalessa', 'In Ghar', 'In Guezzam', 'Idles', 'Tazrouk', 'Tin Zaouatine'],
  12: ['Tébessa', 'Bir El Ater', 'Cheria', 'El Kouif', 'El Malabiod', 'Ouenza', 'Hammamet', 'Negrine'],
  13: ['Tlemcen', 'Maghnia', 'Mansourah', 'Chetouane', 'Nedroma', 'Remchi', 'Sabra', 'Ghazaouet', 'Honnaine'],
  14: ['Tiaret', 'Sougueur', 'Meghila', 'Frenda', 'Ain Deheb', 'Mahdia', 'Rahouia', 'Hamadia', 'Ksar Chellala'],
  15: ['Tizi Ouzou', 'Draa Ben Khedda', 'Azazga', 'Larbaa Nath Irathen', 'Tigzirt', 'Ouaguenoun', 'Freha', 'Boghni'],
  16: ['Alger Centre', 'Sidi M\'Hamed', 'El Madania', 'Belouizdad', 'Bab El Oued', 'Casbah', 'Oued Koriche', 'Bologhine', 'Rais Hamidou', 'Bir Mourad Rais', 'Birkhadem', 'Hydra', 'Saoula', 'El Biar', 'Ben Aknoun', 'Bouzareah', 'Cherea', 'El Hammamet', 'El Harrach', 'Bourouba', 'Oued Smar', 'Bachdjerrah', 'Hussey Dey', 'Kouba', 'Magharia', 'Beniel', 'Dar El Beida', 'Bab Ezzouar', 'Bordj El Kiffan', 'Mohammadia', 'Birtouta', 'Tessala El Merdja', 'Ouled Chebel', 'Zeralda', 'Staoueli', 'Souidania', 'Cheraga', 'Ouled Fayet', 'Draria', 'El Achour', 'Baba Hassen', 'Douera', 'Khraicia', 'Rouiba', 'Reghaia', 'Ain Taya', 'Hraoua', 'Bordj El Bahri', 'El Marsa'],
  17: ['Djelfa', 'Ain Oussera', 'Hassi Bahbah', 'Messaad', 'Birine', 'Dar Chioukh', 'Charef', 'El Idrissia'],
  18: ['Jijel', 'El Milia', 'Taher', 'Chekfa', 'El Aouana', 'Texenna', 'Djimla', 'Kaous'],
  19: ['Sétif', 'El Eulma', 'Ain Arnat', 'Ain Oulmene', 'Ain Azel', 'Bougaa', 'Hammam Sokhna', 'Amoucha', 'Salah Bey'],
  20: ['Saïda', 'Ain El Hadjar', 'Youb', 'Sidi Boubekeur', 'Ouled Brahim', 'Hassasna', 'Maamora'],
  21: ['Skikda', 'El Harrouch', 'Tamalous', 'Collo', 'Azzaba', 'Ben Azzouz', 'Ramdane Djamel', 'Sidi Mezghiche'],
  22: ['Sidi Bel Abbès', 'Tessala', 'Sidi Lahcene', 'Sidi Ali Boussidi', 'Tenira', 'Moulay Slissen', 'Telagh', 'Sfisef'],
  23: ['Annaba', 'El Bouni', 'Berrahal', 'El Hadjar', 'Sidi Amar', 'Ain Berda', 'Chetaibi', 'Seraidi'],
  24: ['Guelma', 'Oued Zenati', 'Ain Makhlouf', 'Heliopolis', 'Guelaat Bou Sbaa', 'Hammam Debagh', 'Bouchegouf'],
  25: ['Constantine', 'El Khroub', 'Ain Smara', 'Didouche Mourad', 'Hamma Bouziane', 'Zighoud Youcef', 'Ibn Ziad', 'Ouled Rahmoune', 'Ain Abid', 'Ben Badis', 'Beni Hamidane', 'Messaoud Boudjriou'],
  26: ['Médéa', 'Berrouaghia', 'Ksar El Boukhari', 'El Omaria', 'Guelb El Kebir', 'Tablat', 'Ain Boucif'],
  27: ['Mostaganem', 'Ain Nouissy', 'Hassi Mameche', 'Mazagran', 'Stidia', 'Ain Tedles', 'Sidi Ali', 'Bouguirat'],
  28: ['M\'Sila', 'Bou Saada', 'Sidi Aissa', 'Ain El Hadjel', 'Hammam Dalaa', 'Ouled Derradj', 'Magra'],
  29: ['Mascara', 'Bou Hanifia', 'Tighennif', 'Ghriss', 'Oued El Abtal', 'Mohammadia', 'Sig', 'Zahana'],
  30: ['Ouargla', 'Ain Beida', 'N\'Goussa', 'Hassi Messaoud', 'Rouissat', 'Sidi Khouiled'],
  31: ['Oran', 'Es Senia', 'Bir El Djir', 'Arzew', 'Ain Turk', 'Gdyel', 'Hassi Bounif', 'Hassi Ben Okba', 'Misserghin', 'Boutlelis', 'Mers El Kebir'],
  32: ['El Bayadh', 'Rogassa', 'Brezina', 'El Abiodh Sidi Cheikh', 'Boualem', 'Labiodh Sidi Cheikh'],
  33: ['Illizi', 'Djanet', 'Debdeb', 'Bordj Omar Driss', 'In Amenas', 'Bordj El Haouas'],
  34: ['Bordj Bou Arréridj', 'Ras El Oued', 'Bordj Zemoura', 'Mansoura', 'Ain Taghrout', 'Bordj Ghedir'],
  35: ['Boumerdès', 'Boudouaou', 'Dellys', 'Thenia', 'Isser', 'Zemmouri', 'Bordj Menaiel', 'Corso', 'Tidjelabine'],
  36: ['El Tarf', 'Bouhadjar', 'Ben M\'Hidi', 'Drean', 'El Kala', 'Besbes', 'Ain El Assel'],
  37: ['Tindouf', 'Oum El Assel'],
  38: ['Tissemsilt', 'Theniet El Had', 'Lardjem', 'Bordj Bou Naama', 'Lazharia', 'Ammari'],
  39: ['El Oued', 'Robbah', 'Bayadha', 'Guemar', 'Kouinine', 'Reguiba', 'Debila', 'Hassi Khalifa'],
  40: ['Khenchela', 'Kais', 'Bouhmama', 'Chechar', 'El Hamma', 'Ain Touila', 'Babar'],
  41: ['Souk Ahras', 'Sedrata', 'Medaourouch', 'Taoura', 'Merahna', 'Haddada', 'Bir Bou Haouch'],
  42: ['Tipaza', 'Cherchell', 'Bou Ismail', 'Ahmar El Ain', 'Kolea', 'Douaouda', 'Hadjout', 'Sidi Amar', 'Gouraya'],
  43: ['Mila', 'Chelghoum Laid', 'Tadjenanet', 'Grarem Gouga', 'Oued Endja', 'Rouached', 'Ferdjioua'],
  44: ['Aïn Defla', 'Khemis Miliana', 'Miliana', 'El Attaf', 'Djelida', 'El Abadia', 'Rouina'],
  45: ['Naâma', 'Mecheria', 'Ain Sefra', 'Tiout', 'Sfissifa', 'Moghrar', 'Assela'],
  46: ['Aïn Témouchent', 'Hammam Bouhadjar', 'Beni Saf', 'El Amria', 'El Malah', 'Ain Kihel'],
  47: ['Ghardaïa', 'El Menia', 'Metlili', 'Berriane', 'Guerrara', 'Zelfana', 'Bounoura'],
  48: ['Relizane', 'Oued Rhiou', 'Mazouna', 'Sidi M\'Hamed Ben Ali', 'Ammi Moussa', 'Zemmora', 'Djidioua'],
  49: ['Timimoun', 'Ouled Said', 'Tinerkouk', 'Charouine'],
  50: ['Bordj Badji Mokhtar', 'Timiaouine'],
  51: ['Ouled Djellal', 'Sidi Khaled', 'Ras El Miad'],
  52: ['Béni Abbès', 'Kerzaz', 'El Ouata', 'Igli'],
  53: ['In Salah', 'Foggaret Ezzoua', 'Inghar'],
  54: ['In Guezzam', 'Tin Zaouatine'],
  55: ['Touggourt', 'Temacine', 'Megarine', 'Nezla'],
  56: ['Djanet', 'Bordj El Haouas'],
  57: ['El M\'Ghair', 'Djamaa', 'Oum Touyour'],
  58: ['El Meniaa', 'Hassi Gara']
};

export const CAR_BRANDS = [
  'Abarth', 'Alfa Romeo', 'Aston Martin', 'Audi', 'Bentley', 'BMW', 'Bugatti', 'Cadillac', 'Chery', 'Chevrolet', 
  'Chrysler', 'Citroën', 'Dacia', 'Daewoo', 'DFSK', 'Dodge', 'DS Automobiles', 'Ferrari', 'Fiat', 'Ford', 'Geely', 
  'GMC', 'Great Wall', 'Haval', 'Honda', 'Hummer', 'Hyundai', 'Infiniti', 'Isuzu', 'Iveco', 'JAC', 'Jaguar', 
  'Jeep', 'Kia', 'Lamborghini', 'Lancia', 'Land Rover', 'Lexus', 'Mahindra', 'Maserati', 'Mazda', 'McLaren', 
  'Mercedes-Benz', 'MG', 'Mini', 'Mitsubishi', 'Nissan', 'Opel', 'Peugeot', 'Porsche', 'Renault', 'Rolls-Royce', 
  'Seat', 'Skoda', 'Smart', 'SsangYong', 'Subaru', 'Suzuki', 'Tesla', 'Toyota', 'Volkswagen', 'Volvo'
];

export const NAV_LINKS = [
  { label: 'Home', view: PageView.HOME },
  { label: 'Garage', view: PageView.GARAGE },
  { label: 'Spare Parts', view: PageView.PARTS },
  { label: 'Towing', view: PageView.TOWING },
];